#server:
#  port: 8080
#  servlet:
#    context-path: /
#    encoding:
#      charset: utf-8

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/week3
#    username:
    username: root
    password:
    url: jdbc:h2:~/testCode

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

mybatis:
  type-aliases-package: com/example/week3_spring.domain
  mapper-locations: mappers/*.xml